README.md
README.zh-CN.md

docs: document link

---

README.md
README.zh-CN.md

doc: update readme

---

.changeset/wise-geese-camp.md
bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/public/bootstrap.min.css
src/ConfigProvider/hooks/useConfig.ts
src/ConfigProvider/index.md
src/types/config.ts

```js
<ConfigProvider graph={{ animation: false // 统一将关系图组件的动画关闭 }}>
<GPTVis>{content}</GPTVis>
</ConfigProvider>
```

feat: graph supports global configuration

---

.changeset/rich-horses-look.md
src/Text/VisText.tsx
src/Text/demos/markdown.tsx

| ![image](https://github.com/user-attachments/assets/ecb6cbea-4b52-44f1-8567-354b8f7b0782)  | ![image](https://github.com/user-attachments/assets/48b86d97-ce74-4842-818f-2e4d24293f4e) |

fix(text): vis-text use parent container font-size

---

docs/guide/antd-design-x.md

docs: Update antd-design-x.md

---

package.json

dcos: Update homepage url

---

.dumirc.ts

docs: fix typo in .dumirc.ts

---

README.ja-JP.md
README.md
README.zh-CN.md

I created Japanese translated README.

docs: add Japanese README

---

src/ConfigProvider/hooks/useConfig.ts
src/FlowDiagram/helper.ts
src/FlowDiagram/index.tsx

use snake layout when data is linear structure
| <img width="200" src="https://github.com/user-attachments/assets/91672a00-211e-4373-b638-aec0b0e00a61" />     | <img width="200" src="https://github.com/user-attachments/assets/11c5778c-60ff-45a7-a5f5-6a86255943dc" />    |

feat(comp): optimize flow diagram layout

---

.changeset/silent-buckets-grab.md
src/Text/utils/useAntdDarkAlgorithm.ts

fix:  theme undefined with antd@4

---

.changeset/tasty-cougars-hide.md

chore: update change set

---

README.md

chore: update live demo in README.md file

---

.changeset/thick-garlics-enter.md
src/HeatMap/index.tsx
src/PathMap/index.tsx
src/PinMap/index.tsx
src/utils/map/style.ts

fix: rerender for pinmap

---

.changeset/purple-wolves-enjoy.md
src/utils/map/view.ts

fix: map bound

---

bindings/gpt-vis-ssr/src/utils.ts

feat: build bug fixed

---

bindings/dify-plugin-visualization/manifest.yaml
bindings/dify-plugin-visualization/tools/generate_area_chart.py
bindings/dify-plugin-visualization/tools/generate_bar_chart.py
bindings/dify-plugin-visualization/tools/generate_chart_url.py
bindings/dify-plugin-visualization/tools/generate_column_chart.py
bindings/dify-plugin-visualization/tools/generate_column_chart.yaml
bindings/dify-plugin-visualization/tools/generate_dual_axes_chart.py
bindings/dify-plugin-visualization/tools/generate_fishbone_diagram.py
bindings/dify-plugin-visualization/tools/generate_flow_diagram.py
bindings/dify-plugin-visualization/tools/generate_histogram_chart.py
bindings/dify-plugin-visualization/tools/generate_line_chart.py
bindings/dify-plugin-visualization/tools/generate_line_chart.yaml
bindings/dify-plugin-visualization/tools/generate_mind_map.py
bindings/dify-plugin-visualization/tools/generate_network_graph.py
bindings/dify-plugin-visualization/tools/generate_pie_chart.py
bindings/dify-plugin-visualization/tools/generate_pie_chart.yaml
bindings/dify-plugin-visualization/tools/generate_radar_chart.py
bindings/dify-plugin-visualization/tools/generate_scatter_chart.py
bindings/dify-plugin-visualization/tools/generate_treemap_chart.py
bindings/dify-plugin-visualization/tools/generate_word_cloud_chart.py
bindings/dify-plugin-visualization/tools/generate_word_cloud_chart.yaml
bindings/dify-plugin-visualization/tools/validate.py

feat: valid treedata and edge node data

---

bindings/gpt-vis-ssr/package.json
bindings/gpt-vis-ssr/src/vis/funnel.ts

chore: fix typo

---

bindings/gpt-vis-ssr/package.json
bindings/gpt-vis-ssr/src/types.ts

feat: update version

---

package.json
src/ChartCodeRender/ErrorComponent.tsx
src/ChartCodeRender/VisChart.tsx
src/ChartCodeRender/demos/errorRender.tsx
src/ChartCodeRender/index.md
src/ChartCodeRender/index.tsx
src/ChartCodeRender/type.ts
src/index.ts

feat: add errorRender

---

bindings/gpt-vis-ssr/package.json

feat: version update to publish rough

---

.changeset/brave-buttons-wait.md
src/ChartCodeRender/VisChart.tsx

feat: add copy feedback

---

src/ChartCodeRender/demos/errorRender.tsx
src/ChartCodeRender/index.md
src/ChartCodeRender/styles.ts

fix: error render style

---

.changeset/three-deer-open.md
src/ChartCodeRender/styles.ts

fix: css error

---

bindings/gpt-vis-ssr/package.json
bindings/gpt-vis-ssr/src/vis/area.ts
bindings/gpt-vis-ssr/src/vis/bar.ts
bindings/gpt-vis-ssr/src/vis/boxplot.ts
bindings/gpt-vis-ssr/src/vis/column.ts
bindings/gpt-vis-ssr/src/vis/dual-axes.ts
bindings/gpt-vis-ssr/src/vis/fishbone-diagram.ts
bindings/gpt-vis-ssr/src/vis/flow-diagram.ts
bindings/gpt-vis-ssr/src/vis/funnel.ts
bindings/gpt-vis-ssr/src/vis/histogram.ts
bindings/gpt-vis-ssr/src/vis/line.ts
bindings/gpt-vis-ssr/src/vis/liquid.ts
bindings/gpt-vis-ssr/src/vis/mind-map.ts
bindings/gpt-vis-ssr/src/vis/network-graph.ts
bindings/gpt-vis-ssr/src/vis/organization-chart.ts
bindings/gpt-vis-ssr/src/vis/pie.ts
bindings/gpt-vis-ssr/src/vis/radar.ts
bindings/gpt-vis-ssr/src/vis/sankey.ts
bindings/gpt-vis-ssr/src/vis/scatter.ts
bindings/gpt-vis-ssr/src/vis/treemap.ts
bindings/gpt-vis-ssr/src/vis/venn.ts
bindings/gpt-vis-ssr/src/vis/violin.ts
bindings/gpt-vis-ssr/src/vis/word-cloud.ts

refactor: move `texture` to style.texture

---

bindings/gpt-vis-ssr/package.json

chore: version

---

.changeset/tiny-games-joke.md

feat: add changeset

---

bindings/gpt-vis-ssr/package.json

chore: gpt-vis-ssr 0.3.0
